### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by andrewramsay** [NPLinker/nplinker#15]
Not immediately urgent, but before the first version is released it would be good to package the code up nicely (maybe [using this suggested structure](https://drivendata.github.io/cookiecutter-data-science/#directory-structure) for data science projects?), and make it available on pypi so it can be installed with pip.

**Comment by andrewramsay** [comment]
This would still be useful but less important now we have a Docker image for running the webapp which will probably be the easier option for most users.

**Comment by CunliangGeng** [comment]
After discussing with Justin, we are going to make it as a python package. Our [python template ](https://github.com/NLeSC/python-template) will be used.
