### ISSUE TITLE
Matching compound names from GNPS to MiBIG

### ISSUE THREAD

**Issue by sdrogers** [NPLinker/nplinker#3]
This is a bit of a mess (and will be always I think).
We could store a dictionary of the names that appear in GNPS (LibraryID) which seem to be slightly different from the ones that are in the GNPS library MGF files.
Also need to be able to handle the dereplicator results that appear in the LibraryID column and dereplicator results from dereplicator (should be cleaner)
Also, varquest...etc

**Comment by justinjjvanderhooft** [comment]
Indeed, over the coming months I will try to validate links within the iOMEGA project but it will remain tricky indeed. Also, I can add SMILES to GNPS library IDs but will need to find some time to do it as we will need to double check the identifications....

**Comment by justinjjvanderhooft** [comment]
Indeed, over the coming months I will try to validate links within the iOMEGA project but it will remain tricky indeed. Also, I can add SMILES to GNPS library IDs but will need to find some time to do it as we will need to double check the identifications....

**Comment by sdrogers** [comment]
It seems though that GNPS doesn't necessarily provide the "IDs" - in the Crusemann file I'm working from it has compound names...IDs would be more helpful.

**Comment by sdrogers** [comment]
Also, Inchikey maybe better than smiles (or both)

**Comment by justinjjvanderhooft** [comment]
What do you mean with IDs? I meant the compound names but they are not always completely unambiguous....

**Comment by sdrogers** [comment]
The gnps library spectra have official IDs (CCMSXXXXXXXX) but this isn't in the output. In the output is the name "Staurosporine" which is also not identical to the names in the GNPS library MGF file (where the adduct is also present Staurosporine M+H or something

**Comment by sdrogers** [comment]
I suspect we'll end up with a method that just tries lots of ways of comparing the two names together

**Comment by justinjjvanderhooft** [comment]
Got it - you are right. Better to communicate with InchiKeys and SMILES/SMARTS....

**Comment by CunliangGeng** [comment]
I assume this issue has been solved, please reopen it if not.
