### ISSUE TITLE
Create independent repo for webapp?

### ISSUE THREAD

**Issue by CunliangGeng** [NPLinker/nplinker#72]
As issue #71 mentioned, we're planning to restructure this repo and make nplinker (`prototype`,  let's call it backend) as a python package.

After checking the code, it looks that nplinker backend and webapp are quite independent and could be split to two independent repos. The splitting will make the whole project more modular and help much for further development and maintenance.

There could be some serious drawbacks I did not see, what comments do you have? @andrewramsay @justinjjvanderhooft @gcroci2

**Comment by andrewramsay** [comment]
I think it makes a lot of sense to do that, there's no real reason they're both in the same repo other than it made the early development process a bit easier and nobody was too concerned about packaging back then. 

You might want to change some things in [server_lifecycle.py](https://github.com/NPLinker/nplinker/blob/master/webapp/npapp/server_lifecycle.py) where it currently just relies on having an env var called `NPLINKER_CONFIG` to determine where to find the configuration file. 

Other than that I think the rest of the webapp code simply passes around an instance of the NPLinker class and uses its existing API to do things. As long as the webapp repo is updated to track any breaking API changes I don't think there would be any problems splitting them up and it should definitely help future maintenance and development.

**Comment by justinjjvanderhooft** [comment]
@andrewramsay thanks for your insights and I agree. @CunliangGeng, you are right, the current versioning is based on the update(d) docker image - this is something we can change of course.

**Comment by andrewramsay** [comment]
Yes, I've only been updating the changelog when I was also building a new Docker image and tagging a new release. It covers changes from both the webapp and backend but I only added the Changelog file relatively recently and most recent changes have been to the backend, so it looks more focused on that.

**Comment by CunliangGeng** [comment]
Thank you both 👍   Now it's clear to me. I'll then start the restructuring and splitting work :-)
