### ISSUE TITLE
Important: Stop committing until restructuring is done 

### ISSUE THREAD

**Issue by CunliangGeng** [NPLinker/nplinker#73]
Hi all @andrewramsay @justinjjvanderhooft @sdrogers @gcroci2 @louwenjjr 

I'm going to restructure this repo and there will be a broken change on the structure and files of this repo (#71 ). 

Before I do that, **could you please check the following in this week?**
- commit all your work and pull request to `master` branch
- then stop working on this repo until the structuring is done (you'll receive a notification)

If you have no commits to push, it's great! 
🟢 Please leave me a pass comment, I could start structuring then. 

Thank you!

**Comment by justinjjvanderhooft** [comment]
I have nothing ongoing! FYI: reviewers of NPClassScore may visit the GitHub to check the code or try it on example data.

**Comment by andrewramsay** [comment]
> FYI: reviewers of NPClassScore may visit the GitHub to check the code or try it on example data.

Worth adding a temporary note to the README explaining that restructuring is ongoing and linking to the current latest master commit? That way they can easily retrieve a working version if they want to run anything.

**Comment by justinjjvanderhooft** [comment]
good suggestion @andrewramsay - @CunliangGeng could you do that? Thx!

**Comment by CunliangGeng** [comment]
Thank you all! 

@justinjjvanderhooft  no worry about the reviewing, nothing will be changed on the current default branch `master`. Users can still use it as before even during restructuring.

All restructuring changes will be on a new branch `main` and it'll be set as the default branch of this repo when we make sure everything goes well.

**Comment by CunliangGeng** [comment]
🎉🎉🎉 Restructuring is done!

By restructuring NPLinker codebase with eScience center python template, we split the codebase to two repos, enable packaging, github actions and collaborative dev guide.

With the new restructured codebase, we released  

- [NPLinker](https://github.com/NPLinker/nplinker) v1.3.0, it's backend and now enabled as python package ([release log ](https://github.com/NPLinker/nplinker/releases/tag/v1.3.0)and [pypi](https://pypi.org/project/nplinker))
   - the default branch was changed from `master` to `main`
- [NPLinker Webapp](https://github.com/NPLinker/nplinker-webapp) v0.1.0, it's frontend, [release log](https://github.com/NPLinker/nplinker-webapp/releases/tag/v0.1.0)
- [Docker image](https://hub.docker.com/r/nlesc/nplinker) `nlesc/nplinker:frontend0.1.0-backend1.3.0`

Now you can restart working on NPLinker code. To make collaborative dev easier,  have a look at `README.dev.md` ([e.g. this one](https://github.com/NPLinker/nplinker/blob/main/README.dev.md)) and `CONTRIBUTING.md` ([e.g. this one](https://github.com/NPLinker/nplinker/blob/main/CONTRIBUTING.md)).

**Comment by sdrogers** [comment]
Nothing from me either
