### ISSUE TITLE
Documentation on readthedocs.io

### ISSUE THREAD

**Issue by andrewramsay** [NPLinker/nplinker#74]
Something I think we have overlooked so far is the auto-generated documentation at https://nplinker.readthedocs.io/en/latest/. 

It's slightly broken at the moment because it's missing the NPLinker class documentation but it's set up to automatically rebuild the docs every time a commit is made (through a webhook), I think it'd be useful to keep it around as up-to-date API information for anyone not using the webapp. 

I used my personal readthedocs account for this but it looks like I can add other readthedocs accounts as maintainers, so that could be a simple way to transfer ownership to an eScience Center account. 

The missing NPLinker class documentation can easily be restored with a tweak to the Sphinx config file but I'll wait until after the refactoring is complete to commit that.

**Comment by CunliangGeng** [comment]
@andrewramsay there seems no way to transfer that, but adding more maintainers. could you please add me as a maintainer? my username is [CunliangGeng](https://readthedocs.org/profiles/CunliangGeng/)

@justinjjvanderhooft yep, docs for end users and developers are in the plan.

**Comment by andrewramsay** [comment]
I've added you as a maintainer now

**Comment by justinjjvanderhooft** [comment]
Thanks @andrewramsay - perhaps handy to add me as well? 😎

**Comment by CunliangGeng** [comment]
Yes, thanks, it works.

**Comment by andrewramsay** [comment]
@justinjjvanderhooft sure, can do - do you already have an account there? I couldn't see one matching your GitHub username.

**Comment by CunliangGeng** [comment]
The issue is solved by #218.
